import Navbar from "@/components/Navbar";
import Head from "next/head";
import React from "react";

const Contact = () => {
  return (
    <div>
      <Head>
        <title>Advanced Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="text-center my-8">
        <h1 className="font-semibold text-3xl mb-4">Contact us</h1>
        <iframe
          src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d14536.353500710782!2d88.6003293642206!3d24.37822888444034!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sbd!4v1680758640647!5m2!1sen!2sbd"
          width="100%"
          height="400"
          title="map"
          style={{ border: 0 }}
          allowFullScreen={true}
          referrerPolicy="no-referrer-when-downgrade"
        ></iframe>
      </div>
    </div>
  );
};

export default Contact;
