import Navbar from "@/components/Navbar";
import dynamic from "next/dynamic";
import React, { useEffect, useState } from "react";
import { ContentState, EditorState, convertToRaw } from "draft-js";
import draftToMarkdown from "draftjs-to-markdown";
import { editABlog, postBlog } from "@/config/axiosInstance";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { editBlog, editBlogSelector } from "@/redux/editBlogSlice";
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import { userSelector } from "@/redux/userSlice";

const CreatePost = () => {
  const { blog } = useSelector(editBlogSelector);
  const { user } = useSelector(userSelector);

  const dispatch = useDispatch();
  const router = useRouter();

  const [loading, setLoading] = useState(false);
  const [prevTitle, setPrevTitle] = useState(blog?.title ? blog.title : "");
  const [file, setFile] = useState(null);
  const [showValidate, setShowValidate] = useState(false);

  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
    reset,
  } = useForm();

  const newTitle = watch("title");

  const RichEditor = dynamic(() => import("../components/RichEditor"), {
    ssr: false,
  });

  const [editorState, setEditorState] = useState(() =>
    EditorState.createEmpty()
  );

  useEffect(() => {
    // Loads previous data when being edited.
    if (blog?.body) {
      const previousEditorState = EditorState.createWithContent(
        ContentState.createFromText(blog.body)
      );
      setEditorState(previousEditorState);
    }

    //Dismiss previous data when page is unmounted
    const handleRouteChange = () => {
      dispatch(editBlog({}));
    };
    router.events.on("routeChangeComplete", handleRouteChange);
    return () => {
      router.events.off("routeChangeComplete", handleRouteChange);
    };
  }, []);

  const body = draftToMarkdown(convertToRaw(editorState.getCurrentContent()));

  //Check if the content body has anything
  const contentState = editorState.getCurrentContent();
  const contentIsEmpty = !contentState.hasText();

  const handlePost = async () => {
    // Checing if the content field is empty
    if (contentIsEmpty) {
      setShowValidate(true);
      return;
    } else {
      setLoading(true);

      // Check if the blog has anything in it,
      // If it doesn't have anything that means new blog is created.
      if (Object.keys(blog).length === 0) {
        let image;

        // Check if the blog has Image. If it has first it will upload the image to cloudinary.
        if (file) {
          const formData = new FormData();
          formData.append("file", file);
          formData.append("upload_preset", "advanced-blog");
          formData.append("cloud_name", "dnqvwwxzv");
          try {
            const res = await fetch(
              "https://api.cloudinary.com/v1_1/dnqvwwxzv/image/upload",
              {
                method: "POST",
                body: formData,
              }
            );
            const picData = await res.json();
            image = picData?.url?.toString();
          } catch (error) {
            console.log(error);
          }
        }

        // Post a new blog
        try {
          const { data } = await postBlog(newTitle, body, user._id, image);
          setLoading(false);
          reset();
          setEditorState(() => EditorState.createEmpty());
          router.push("/");
        } catch (error) {
          setLoading(false);
          console.log(error);
        }
      } else {
        // Submit an edited blog
        try {
          const { data } = await editABlog(blog?._id, newTitle, body);
          dispatch(editBlog({}));
          router.replace("/");
          setLoading(false);
          reset();
        } catch (error) {
          console.log(error);
          setLoading(false);
        }
      }
    }
  };
  return (
    <div>
      <Head>
        <title>Advanced Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="mx-auto text-center mb-6">
        <p className="font-semibold text-4xl mt-4 mb-8">
          {blog?.body ? "Edit Blog" : "Post a Blog"}
        </p>
        <form onSubmit={handleSubmit(handlePost)} className="h-full">
          <br />
          <input
            type="text"
            placeholder="Blog Title"
            // value={title}
            // onChange={(e) => setTitle(e.target.value)}
            defaultValue={prevTitle}
            className="px-4 py-2 mb-8 w-2/4 rounded-md focus:rounded-none border-b-2 outline-none focus:border-slate-700"
            {...register("title", { required: true })}
          />
          {errors.title && (
            <span className="text-xs text-red-600">Title is required</span>
          )}
          <RichEditor
            editorState={editorState}
            setEditorState={setEditorState}
          />
          {contentIsEmpty && showValidate && (
            <p className="text-xs text-red-600">Content body is required</p>
          )}
          {Object.keys(blog).length === 0 && (
            <input
              type="file"
              onChange={(e) => setFile(e.target.files[0])}
              className="file-input file-input-bordered w-full max-w-xs my-4 rounded-md"
            />
          )}
          <br />
          {blog?.body ? (
            <button
              className={`btn ${
                loading && "loading btn-disabled"
              } text-white rounded-md`}
            >
              Save Edit
            </button>
          ) : (
            <button
              type="submit"
              className={`btn ${
                loading && "loading btn-disabled"
              } text-white rounded-md`}
            >
              Post blog
            </button>
          )}
        </form>
      </div>
    </div>
  );
};

export default CreatePost;
