import Navbar from "@/components/Navbar";
import dynamic from "next/dynamic";
import React, { useState } from "react";
import { EditorState, convertToRaw } from "draft-js";
import draftToMarkdown from "draftjs-to-markdown";
import { postBlog } from "@/config/axiosInstance";
import Head from "next/head";

const CreatePost = () => {
  const [loading, setLoading] = useState(false);
  // const [postBody, setpostBody] = useState();
  const [title, setTitle] = useState("");
  const [file, setFile] = useState(null);

  const RichEditor = dynamic(() => import("../components/RichEditor"), {
    ssr: false,
  });

  const [editorState, setEditorState] = useState(() =>
    EditorState.createEmpty()
  );
  const body = draftToMarkdown(convertToRaw(editorState.getCurrentContent()));

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);

    let image;
    if (file) {
      const formData = new FormData();
      formData.append("file", file);
      formData.append("upload_preset", "advanced-blog");
      formData.append("cloud_name", "dnqvwwxzv");
      try {
        console.log("pic uploading");
        const res = await fetch(
          "https://api.cloudinary.com/v1_1/dnqvwwxzv/image/upload",
          {
            method: "POST",
            body: formData,
          }
        );
        const picData = await res.json();
        image = picData?.url?.toString();
        // setPicture(picData?.url?.toString());
      } catch (error) {
        console.log(error);
      }
    }
    try {
      const { data } = await postBlog(title, body, image);
      setLoading(false);
      setTitle("");
      setEditorState(() => EditorState.createEmpty());
      console.log(data);
    } catch (error) {
      setLoading(false);
      console.log(error);
    }
  };
  return (
    <div>
      <Head>
        <title>Advanced Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="mx-auto text-center mb-6">
        <p className="font-semibold text-4xl mt-4 mb-8">Post a blog</p>
        <form onSubmit={handleSubmit} className="h-full">
          <input
            type="text"
            placeholder="Blog Title"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            className="px-4 py-2 mb-8 w-2/4 rounded-md focus:rounded-none border-b-2 outline-none focus:border-slate-700"
          />
          <RichEditor
            editorState={editorState}
            setEditorState={setEditorState}
          />
          <input
            type="file"
            onChange={(e) => setFile(e.target.files[0])}
            className="file-input file-input-bordered w-full max-w-xs my-4 rounded-md"
          />
          <br />
          <button
            type="submit"
            className={`btn ${
              loading && "loading btn-disabled"
            } text-white rounded-md`}
          >
            Post blog
          </button>
        </form>
      </div>
    </div>
  );
};

export default CreatePost;
