import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import HeroCard from "@/components/HeroCard";
import { useEffect, useState } from "react";
import Cookies from "js-cookie";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [user, setUser] = useState();

  useEffect(() => {
    const localUserInfo = JSON.parse(localStorage.getItem("blogUser"));
    setUser(localUserInfo);
  }, []);

  return (
    <>
      <Head>
        <title>Advanced Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Navbar user={user} />
        <div className="flex flex-col md:flex-row gap-8 justify-center my-6">
          <HeroCard />
          <HeroCard />
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps({ req }) {
  if (!req.headers.cookie) {
    return {
      redirect: {
        destination: "/signIn",
      },
    };
  }
  return {
    props: {},
  };
}
